# Generated by Django 4.2.5 on 2023-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('zona_residencia', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('rh', models.CharField(max_length=100)),
            ],
        ),
    ]
