# Generated by Django 4.1.7 on 2023-09-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0002_practicante'),
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado_cita', models.CharField(max_length=255)),
                ('id_consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.consultorio')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('id_practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.practicante')),
            ],
        ),
    ]
